// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAjnQGr_w2SN7J2MaIJMxXVOmTbbUWUss',
    appId: '1:657184693769:web:09cd3260ff785d8ffde2d8',
    messagingSenderId: '657184693769',
    projectId: 'wedapp-633fb',
    authDomain: 'wedapp-633fb.firebaseapp.com',
    storageBucket: 'wedapp-633fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC41pRbuERN3x_w4PPqQJMvxyZNP3t6wU8',
    appId: '1:657184693769:android:55ba4a7e66ec513bfde2d8',
    messagingSenderId: '657184693769',
    projectId: 'wedapp-633fb',
    storageBucket: 'wedapp-633fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaB9F_A1WbUjsN-3uHS1rmb6q39bZF_KM',
    appId: '1:657184693769:ios:c34aa50fab39cbcefde2d8',
    messagingSenderId: '657184693769',
    projectId: 'wedapp-633fb',
    storageBucket: 'wedapp-633fb.firebasestorage.app',
    iosBundleId: 'com.example.wed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaB9F_A1WbUjsN-3uHS1rmb6q39bZF_KM',
    appId: '1:657184693769:ios:c34aa50fab39cbcefde2d8',
    messagingSenderId: '657184693769',
    projectId: 'wedapp-633fb',
    storageBucket: 'wedapp-633fb.firebasestorage.app',
    iosBundleId: 'com.example.wed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAjnQGr_w2SN7J2MaIJMxXVOmTbbUWUss',
    appId: '1:657184693769:web:3bd2adec34ef53e9fde2d8',
    messagingSenderId: '657184693769',
    projectId: 'wedapp-633fb',
    authDomain: 'wedapp-633fb.firebaseapp.com',
    storageBucket: 'wedapp-633fb.firebasestorage.app',
  );
}
